### PR TITLE
Dont remove maxscale binary when stopping via init.d

### PR DESCRIPTION
**Pull request by zytek**

### CODE REVIEW

**Comment by zytek** [comment]
Sorry for the double commit but had to do this via GitHub UI.

Nice surprise when evaluating MaxScale. :boom: 
FYI this was spotted on Ubuntu 12.04.

**Comment by knowak** [comment]
Nice find... :trollface:

**Comment by zytek** [comment]
Ouch, I see this was reported 4 months ago... :-1: 

https://github.com/mariadb-corporation/MaxScale/pull/56

**Comment by markus456** [comment]
Closing, bug is fixed

**Comment by zytek** [comment]
@markus456 I still see offending $PIDFILE variable in the repo, could you elaborate how it was fixed ? It works fine on Ubuntu Trusty, but removes binary on Ubuntu Precise

**Comment by markus456** [comment]
It is fixed in the next release.

**Comment by kolbe** [comment]
This wouldn't be a problem if you properly-quoted the variable expansions. You should *always* quote variable expansions in shell. So, this should be:

killproc -p "$PIDFILE" "$DAEMON"

**Pull request closed without merging**
