### PR TITLE
support mysql8.0.x

### PR DESCRIPTION
**Pull request by happy-v587**
support 8.0.x

### CODE REVIEW

**Comment by markus456** [comment]
This should be done in a more controllable manner so that you can use MySQL connectors with MariaDB. Adding it as a configuration parameter would allow it to be enabled and disabled. Another option might be to see if there's a way to detect that the client doesn't expect the `5.5.5-` prefix and drop it only for those clients.

**Comment by happy-v587** [comment]
Thank you for your reply. Later I will change it as configuration parameter, so that can control it.

**Comment by markus456** [comment]
I think I have to apologize: I misunderstood which version_string this change affected. I thought it was for the one returned by the backend servers themselves that MaxScale uses by default but instead it is for the `version_string` parameter defined in the configuration file.

Now that I've taken a second look at this, I think just the original commit would be adequate as the new parameter doesn't seem to do that much.

**Comment by markus456** [comment]
Additionally, we require that any code contributions to MaxScale are submitted under the BSD-new license. Please indicate this by leaving a comment with the following text:

> I am contributing the new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

**Comment by happy-v587** [comment]
I am contributing the new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

**Review by markus456 — COMMENTED** [review]
I mean that the original commit that only checks whether the `version_string` starts with an 8 would have been enough. Can you use that commit?

**Comment by happy-v587** [comment]
Ok, I've revised it.

**Review by markus456 — APPROVED** [review]

**Review by mbnantti — APPROVED** [review]

**Pull request merged**
