### PR TITLE
MXS-1602 :

### PR DESCRIPTION
**Pull request by ybbct**
to be compatible with python client，add 
1. ignore set session variables 
2. ignore any set names
3. response ping command with full ok packet

### CODE REVIEW

**Review by markus456 — APPROVED** [review]
This looks good as well.

Please indicate that you submit these changes under the BSD-new, as is indicated in the CONTRIBUTING.md document, by commenting with the following text:

I am contributing the new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

**Comment by markus456** [comment]
By the way, if you want these changes to be included in the next 2.1 release of MaxScale, please submit the pull requests against the `2.1` branch. The commit will get into later releases once it is merged to the other release branches.

**Comment by ybbct** [comment]
I am contributing the new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

**Comment by markus456** [comment]
[I cherry-picked the commit](https://github.com/mariadb-corporation/MaxScale/commit/454f195cb03d05e5692f18170fc26db0ed36b27d) into the `2.1` branch. As with the other pull request, it will get merged into `develop` today.

**Pull request closed without merging**
