### PR TITLE
Zendesk's Maxwell Compatibility

### PR DESCRIPTION
**Pull request by adaszko**
Addressed feedback from #118.

### CODE REVIEW

**Comment by MassimilianoPinto** [comment]
Hi,

1)
**router->maxwell_compat** should be used for skipping "SET character_set_results = NULL" as well.

I would suggest to use **router->maxwell_compat** to skip all the "maxwell" queries.

2)
If possible don't save the output of SET (that should be OK packet without messages) and reply to client with "blr_slave_send_ok".

3)
I haven't tested the code yet but I see:
```
+    else if (strcmp(query_text, maxwell_binlog_row_image_query) == 0)
 +    {
 +        char *binlog_row_image = blr_extract_column(router->saved_master.binlog_vars, 2);
```

The number should be 3, isn't it ?

**Comment by adaszko** [comment]
The column numbering starts at 0 or at 1?  It's the third column that I want to extract there.

**Comment by MassimilianoPinto** [comment]
The column number starts at 1.

In the code I see:

```
char *log_bin = blr_extract_column(router->saved_master.binlog_vars, 1);
char *binlog_format = blr_extract_column(router->saved_master.binlog_vars, 2);
char *binlog_row_image = blr_extract_column(router->saved_master.binlog_vars, 2);
```

You need to change the last one from 2 to 3

**Comment by adaszko** [comment]
I'm applying all your suggestions.  One question though:

> I would suggest to use router->maxwell_compat to skip all the "maxwell" queries.

Including the side-effect-free `SELECT`s or you meant just the `SET` query?  I refrained from doing this because it will complicate the state machine transition logic.

**Comment by MassimilianoPinto** [comment]
Hi, please skip all the SETs and you can keep the  SELECTs.

I'm also working on the state machine transition logic for another task, so I could think about that in another time.

**Comment by adaszko** [comment]
Please do not merge before I green-light this.

**Comment by adaszko** [comment]
OK, tested on my end.  The ball is on your side now 🙂

**Comment by MassimilianoPinto** [comment]
The code looks good.

I would only suggest that :

```
SELECT  buf = blr_make_query(router->master, "SELECT @@session.auto_increment_increment AS auto_increme ..."
static const char mysql_connector_server_variables_query[] = "SELECT @@session.auto_increment_increment AS auto_increm...
```

And
```
buf = blr_make_query(router->master, "SET sql_mode='NO_AUTO_CREATE_US ..."
static const char mysql_connector_sql_mode_query[] = "SET sql_mode='NO_AUTO_CREATE_US ..."

```
these queries could be added as defines in blr.h in order to remove duplicates.

**Comment by adaszko** [comment]
> these queries could be added as defines in blr.h in order to remove duplicates.

Good idea.  Done.

**Comment by markus456** [comment]
Similar to other open source projects, the MariaDB Corporation needs to have shared ownership of all code that is included in MaxScale. The easiest way to achieve this is by submitting your code under the BSD-new license.

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

**Comment by adaszko** [comment]
I hereby declare that all the code submitted by me in this pull request are subject to the 3-clause BSD license, including one or several files that are either new files or modified ones.

**Comment by MassimilianoPinto** [comment]
Merge done:

https://github.com/mariadb-corporation/MaxScale/commit/825782799fd799545024dc83bd0a63f427f21c94

**Pull request merged**
