### PR TITLE
Update Hint-Syntax.md

### PR DESCRIPTION
**Pull request by lowenthal-jason**
Added "s" to filters in example [Read Service] as it was confusing trying to get hint routing working correctly.

### CODE REVIEW

**Comment by markus456** [comment]
Similar to other open source projects, the MariaDB Corporation needs to have a shared ownership of all code that is included in MaxScale. The easiest way to achieve this is by submitting your code under the BSD-new license. Are you OK with doing that?

**Comment by lowenthal-jason** [comment]
Absolutely. How do I change that?

**Comment by jhnwkmn** [comment]
Basically you did it already by replying "Absolutely". So all you need to do is to make it clear that you submit your changes under the BSD-new license.

**Comment by lowenthal-jason** [comment]
I submit these changes under BSD-new license.

**Pull request merged**
