### PR TITLE
add missing grant in MaxScale-Tutorial.md

### PR DESCRIPTION
**Pull request by ktugan**
I am contributing the new code of the whole pull request, including one or
several files that are either new files or modified ones, under the BSD-new
license.

### CODE REVIEW

**Review by markus456 — APPROVED** [review]

**Comment by markus456** [comment]
Strictly speaking it's not required by the MaxScale user but the user used for `mariadbmon`. Although not necessary, it is relatively common to combine both accounts into the same one.

**Comment by ktugan** [comment]
Good to know. I can also update the readme to reflect this if interested.

**Comment by markus456** [comment]
I think it would be better to have a separate paragraph that describes the grants that the monitor user requires. To make the documentation easier to maintain, it should also have a link to the documentation of the most frequently used monitors (mariadbmon and galeramon).

**Comment by markus456** [comment]
We'll close this pull request as the tutorials will be formatted a bit differently in the future.

**Pull request closed without merging**
