### PR TITLE
add test for -- style comment

### PR DESCRIPTION
**Pull request by ybbct**
I am contributing the new code of the whole pull request, including one or
several files that are either new files or modified ones, under the BSD-new
license.

### CODE REVIEW

**Comment by markus456** [comment]
I'm looking at the `classify.cc` code and it seems to remove newlines from the SQL:
```c++
	/**Remove newlines*/
        while ((nlptr = strpbrk(strbuff, "\n")) != NULL && (nlptr - strbuff) < strsz)
        {
            memmove(nlptr, nlptr + 1, strsz - (nlptr + 1 - strbuff));
            strsz -= 1;
        }
```

This would explain why the test fails.

Can you check if this happens when you execute the SQL through a running MaxScale?

**Comment by ybbct** [comment]
> Can you check if this happens when you execute the SQL through a running MaxScale?

Yes

2020-12-08 11:42:04   info   : <2> (805306379) > Autocommit: [enabled], trx is [not open], cmd: (0x03) COM_QUERY, plen: 91, type: QUERY_TYPE_READ, stmt: -- is not needed nor is it checked.
UPDATE afsd SET sds = '2020-12-04 06:39:56.164402' ,

**Comment by jhnwkmn** [comment]
> > Can you check if this happens when you execute the SQL through a running MaxScale?
> 
> Yes
> 
> 2020-12-08 11:42:04 info : <2> (805306379) > Autocommit: [enabled], trx is [not open], cmd: (0x03) COM_QUERY, plen: 91, type: QUERY_TYPE_READ, stmt: -- is not needed nor is it checked.
> UPDATE afsd SET sds = '2020-12-04 06:39:56.164402' ,

There is a trailing ,

Is that a syntax error or is it a cut and paste omission, that is, the statement continues to the next line?.

**Comment by ybbct** [comment]
> trailing

yes, the statement continues to the next line

**Comment by ybbct** [comment]
I test in a running MXS, found that keypoint is the tailing dot '.'
```
--- balbaba \n update t1 set a = 1;
```
this statement classifies as write

but 
```
--- balbaba. \n update t1 set a = 1;
```
classifies as read;

**Comment by jhnwkmn** [comment]
> --- balbaba \n update t1 set a = 1;

I could repeat it. Thanks.

**Comment by markus456** [comment]
I'll close this as the bug has been fixed and tested using other means.

**Pull request closed without merging**
