### PR TITLE
TPM filter to log latencies of individual SQL queries

### PR DESCRIPTION
**Pull request by dongyoungy**
I have updated the TPM filter to log not just the latency of a transaction as a whole, but also latencies of individual SQL statements in the transaction. TPM filter uses its 'query_delimiter' to separate latencies of each statement in its log file.

### CODE REVIEW

**Review by markus456 — APPROVED** [review]
Looks good!

**Comment by markus456** [comment]
Similar to other open source projects, the MariaDB Corporation needs to have shared ownership of all code that is included in MaxScale. The easiest way to achieve this is by submitting your code under the BSD-new license.

Please indicate in a comment below that you are contributing your new code of the whole pull request, including one or several files that are either new files or modified ones, under the BSD-new license.

**Comment by dongyoungy** [comment]
I am providing my code of this whole pull request under the BSD-new license.

**Comment by markus456** [comment]
[Merged into develop.](https://github.com/mariadb-corporation/MaxScale/commit/0ddc876567f3c4fe5fcb14d00f4053adf0b363ff)

**Pull request closed without merging**
