### PR TITLE
add support for prepared statements to schemarouter

### PR DESCRIPTION
**Pull request by AgeOfLearning**
I recreated this branch off the develop branch

### CODE REVIEW

**Comment by markus456** [comment]
Similar to other open source projects, the MariaDB Corporation needs to have a shared ownership of all code that is included in MaxScale. The easiest way to achieve this is by submitting your code under the BSD-new license. Are you OK with doing that?

**Comment by AgeOfLearning** [comment]
I am fine with that.

Bill McCaffrey
Chief Technology Officer
Age of Learning, Inc.
101 N. Brand Blvd. Suite 870
Glendale, CA 91203
bill.mccaffrey@aofl.com<mailto:bill.mccaffrey@aofl.com>
818.246.2223

On 10/29/2015 02:06 AM, markus456 wrote:

Similar to other open source projects, the MariaDB Corporation needs to have a shared ownership of all code that is included in MaxScale. The easiest way to achieve this is by submitting your code under the BSD-new license. Are you OK with doing that?

**Comment by markus456** [comment]
I see one issues with the new features. It only supports binary protocol prepared statements which cause non-binary protocol prepared statements to fail. The simple way to handle that would be to just ignore the non-binary prepared statements and should be achievable by removing QUERY_IS_TYPE(qtype, QUERY_TYPE_PREPARE_NAMED_STMT)) from the if on line 2246.

**Comment by markus456** [comment]
Closing this as it hasn't progressed and is based on top of an obsolete version.

**Pull request closed without merging**
