### PR TITLE
MaxWeb project cumulative changes

### PR DESCRIPTION
**Pull request by jfeid**
Additions:
- Redis pipeline filter that logs query info to Redis server
- ZeroMQ pipeline filter that logs query info to ZeroMQ broker
- ZeroMQ consumer that serves as broker
- json module in utils/ for easier handling of json encoding/decoding
- Supporting cmake files

Changes:
- Added skygw_get_realq_type_str() to query_classifer that returns query type as string
- Changed readconn & readwritesplit routers to pass server_id, server_name & server_unique_name query info down the call chain
- Added "show pid" option in debugcmd
- Supporting cmake files

Build instructions:
- Add -DBUILD_REDIS=Y to build the redisfilter module.
- Add -DBUILD_ZMQ=Y to build the zmqfilter module.
- The zeroMQ consumer is build separately under zmq_consumer/ directory similar to rabbitmq_consumer.

Redis Filter options:
- source                The source of the client connection 
- includedServers       When this is not empty filter should accept queries only from this server list e.g: master,slave1
- includedTables        When this is not empty filter should accept queries only from this table list
- user                  A user name to filter on
- match                 Optional text to match against
- exclude               Optional text to match against for exclusion
- saveRealOnly          Save only real queries
- redisHost             Host for ZMQ socket -- Currently ignored
- redisPort             Port for ZMQ port -- Currently ignored 
- redissock     Path to redis.sock -- For now connects only to local Redis server via Unix socket.

ZeroMQ Filter options:
- source                The source of the client connection 
- includedServers       When this is not empty filter should accept queries only from this server list e.g: master,slave1
- includedTables        When this is not empty filter should accept queries only from this table list
- user                  A user name to filter on
- match                 Optional text to match against
- exclude               Optional text to match against for exclusion
- saveRealOnly          Save only real queries
- zmqHost               Host for ZMQ socket
- zmqPort               Port for ZMQ port 

ZeroMQ Consumer options:
- Available via zmq_config.ini place in the same directory as executable

### CODE REVIEW

**Comment by markus456** [comment]
Similar to other open source projects, the MariaDB Corporation needs to have a shared ownership of all code that is included in MaxScale. The easiest way to achieve this is by submitting your code under the BSD-new license. Are you OK with doing that?

**Comment by jfeid** [comment]
Yes, feel free to include the BSD-new license header on the files that is missing.

**Comment by markus456** [comment]
This pull request seems quite old. Are there plans to rebase these changes onto a newer version of MaxScale?

**Comment by jfeid** [comment]
No, currently I do not have the resources to migrate it to newer version.

**Pull request closed without merging**
